// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: feedback.sql

package db

import (
	"context"
)

const createFeedback = `-- name: CreateFeedback :one
insert into feedbacks (userid, feedback)
values ($1, $2)
returning feedback_id, userid, feedback, created_at
`

type CreateFeedbackParams struct {
	Userid   string `json:"userid"`
	Feedback string `json:"feedback"`
}

func (q *Queries) CreateFeedback(ctx context.Context, arg CreateFeedbackParams) (Feedback, error) {
	row := q.db.QueryRowContext(ctx, createFeedback, arg.Userid, arg.Feedback)
	var i Feedback
	err := row.Scan(
		&i.FeedbackID,
		&i.Userid,
		&i.Feedback,
		&i.CreatedAt,
	)
	return i, err
}
