// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
)

type Feedback struct {
	FeedbackID int32        `json:"feedback_id"`
	Userid     string       `json:"userid"`
	Feedback   string       `json:"feedback"`
	CreatedAt  sql.NullTime `json:"created_at"`
}

type User struct {
	Userid    string       `json:"userid"`
	Username  string       `json:"username"`
	CreatedAt sql.NullTime `json:"created_at"`
}
